"""Add user_id to todos table

Revision ID: c394725b5e0c
Revises: 002
Create Date: 2026-01-13 14:07:11.667162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c394725b5e0c'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('idx_todos_completed'), table_name='todos')
    op.drop_index(op.f('idx_todos_created_at'), table_name='todos')
    op.drop_index(op.f('idx_todos_user_id'), table_name='todos')
    op.create_index(op.f('ix_todos_user_id'), 'todos', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_user_id'), table_name='todos')
    op.create_index(op.f('idx_todos_user_id'), 'todos', ['user_id'], unique=False)
    op.create_index(op.f('idx_todos_created_at'), 'todos', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_todos_completed'), 'todos', ['completed'], unique=False)
    op.alter_column('todos', 'user_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
